spring.application.name=jasan.java
spring.datasource.url=jdbc:postgresql://localhost:5432/backend_db
spring.datasource.username=backend_user
spring.datasource.password=NuevaClaveSegura
spring.datasource.driver-class-name=org.postgresql.Driver
